; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega328PB]
;[env:ATmega328P]
platform = atmelavr
board = ATmega328PB
;board = ATmega328P
framework = arduino
board_build.f_cpu = 1000000L
build_flags = -DTWI_FREQ=100000L
upload_port = COM10
upload_protocol = stk500
upload_flags = -pm328pb
;upload_flags = -pm328p
upload_command = avrdude -c$UPLOAD_PROTOCOL -P$UPLOAD_PORT $UPLOAD_FLAGS -U flash:w:$SOURCE:i
lib_deps = 
    labfruits/Mcp320x@^1.4.2
    adafruit/Adafruit DPS310@^1.1.4